kind: Pod
apiVersion: v1
metadata:
  name: kong-app
  labels:
    app: kong
spec:
  containers:
    - name: kong-app
      image: edercesar/kong-k8s:v5

---

kind: Service
apiVersion: v1
metadata:
  name: kong-service
spec:
  selector:
    app: kong
  ports:
    - name: porta8000
      port: 8000 # Default port for kong
    - name: porta8001
      port: 8001

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingres-kong
  labels:
    name: ingress-kong
spec:
  rules:
  - host: eder.com.br
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: kong-service
            port:
              number: 8000



