apiVersion: v1
kind: Pod
metadata:
  name: servicea-pod
  labels:
    name: servicea
spec:
  containers:
  - name: servicea
    image: edercesar/api-conversao:v1
    ports:
      - containerPort: 8080

---
kind: Service
apiVersion: v1
metadata:
  name: servicea
spec:
  selector:
    name: servicea
  ports:
    - port: 8080
